#!/usr/bin/env php
<?php

/*
|----------------------------------------------------------------------
| Lightweight CLI Tool for PHP Server & Custom Commands
|----------------------------------------------------------------------
| This script provides a simple command-line interface (CLI) for managing
| various PHP development tasks. It currently supports the `start` command,
| which launches a PHP built-in server, but additional commands can be easily
| added for other development tasks.
|
| Commands can be run with the following format:
| 
| php lite <command>
|
| Created by: Nihad Namatli
|----------------------------------------------------------------------
*/

/*
|----------------------------------------------------------------------
| Change the Current Working Directory
|----------------------------------------------------------------------
| Ensures the script always runs from the directory where it is located.
| This is useful for resolving relative paths such as 'api', ensuring
| consistency when the script is run from different locations.
*/
chdir(__DIR__);

/*
|----------------------------------------------------------------------
| Get Command-Line Arguments
|----------------------------------------------------------------------
| The first argument (`$argv[1]`) will determine which command to execute.
| If no command is passed, the script will display a list of available 
| commands.
*/
$command = $argv[1] ?? null;

/*
|----------------------------------------------------------------------
| Switch on Command
|----------------------------------------------------------------------
| Depending on the command passed, the script will call 
| the corresponding function.
*/
switch ($command) {
    case 'start':
        /*
        |------------------------------------------------------------------
        | Start PHP Built-in Server
        |------------------------------------------------------------------
        | This command launches the built-in PHP development server, serving 
        | files from the 'api' directory.Once the server is started, the user
        | is prompted with instructions to stop it using Ctrl+C.
        */
        echo "Starting the server at http://localhost:8000...\n";
        echo "Press Ctrl+C to stop the server.\n\n";

        $cmd = 'php -S localhost:8000 -t api'; // Modify this path if needed
        passthru($cmd);
        break;

    
    default:
        /*
        |------------------------------------------------------------------
        | Display Available Commands
        |------------------------------------------------------------------
        | If no command is provided or an invalid command is entered, this 
        | section will output the list of available commands for the user.
        */
        echo "Available commands:\n";
        echo "start   Start the PHP development server\n";
        break;
}
